// "use client";
// import "./globals.css";
// import { ReactNode } from "react";
// import { CopilotKit } from "@copilotkit/react-core"; 
// import { AgentProvider, useAgent } from "./AgentContext";


// function CopilotWrapper({ children }: { children: ReactNode }) {
//   const { agentName } = useAgent();

//   return (
//     <CopilotKit
//       key={agentName}
//       runtimeUrl={`/api/copilotkit/${agentName}`}
//       agent="my_agent"
//     >
//       {children}
//     </CopilotKit>
//   );
// }

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <AgentProvider>
//           <CopilotWrapper>{children}</CopilotWrapper>
//         </AgentProvider>
//       </body>
//     </html>
//   );
// }


// "use client";
import "./globals.css";
import { ReactNode } from "react";
import { AgentProvider } from "./AgentContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Agent Garden",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AgentProvider>
          {children}
        </AgentProvider>
      </body>
    </html>
  );
}